AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CognitoUserPoolName:
    Type: String
    Default: MyUserPool
  
  CognitoUserPoolClientName:
    Type: String
    Default: MyUserPoolClient

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs8.10
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: '{proxy+}'
            Method: get
            # Auth:
            #   DefaultAuthorizer: MyCognitoAuth # OPTIONAL, if you use IAM permissions, specify AWS_IAM.
            #   Authorizers:
            #     MyCognitoAuth:
            #       UserPoolArn: !GetAtt MyCognitoUserPool.Arn # Can also accept an array
                  # Identity: # OPTIONAL
                  #   Header: MyAuthorizationHeader # OPTIONAL; Default: 'Authorization'
                  #   ValidationExpression: myauthvalidationexpression # OPTIONAL
  # MyCognitoUserPool:
  # Type: AWS::Cognito::UserPool
  # Properties:
  #   UserPoolName: !Ref CognitoUserPoolName
  #   # LambdaConfig:
  #   #   PreSignUp: !GetAtt PreSignupLambdaFunction.Arn
  #   Policies:
  #     PasswordPolicy:
  #       MinimumLength: 12
  #   UsernameAttributes:
  #     - email
  #   Schema:
  #     - AttributeDataType: String
  #       Name: email
  #       Required: false

# MyCognitoUserPoolClient:
#   Type: AWS::Cognito::UserPoolClient
#   Properties:
#     UserPoolId: !Ref MyCognitoUserPool
#     ClientName: !Ref CognitoUserPoolClientName
#     GenerateSecret: false